version: '3.10'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/var/lib/redis/data
volumes:
  redis_data:
