"""Add currency to payment

Revision ID: 13e9fd728044
Revises: 3d18c13b9f0e
Create Date: 2025-06-18 15:55:51.102934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13e9fd728044"
down_revision: Union[str, None] = "3d18c13b9f0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("currency", sa.String(length=3), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "currency")
    # ### end Alembic commands ###
