"""Add referrer id column to users

Revision ID: 18a9ca0198e4
Revises: 3605b6582016
Create Date: 2024-08-13 23:02:49.643777

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18a9ca0198e4"
down_revision: Union[str, None] = "3605b6582016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("referrer_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "referrer_id")
    # ### end Alembic commands ###
