"""Add rating column to questions

Revision ID: 71994c9970cd
Revises: 18a9ca0198e4
Create Date: 2024-08-13 23:05:57.095575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71994c9970cd"
down_revision: Union[str, None] = "18a9ca0198e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions", sa.Column("rating", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "rating")
    # ### end Alembic commands ###
