"""Add link column to questions

Revision ID: 81521565f790
Revises: 71994c9970cd
Create Date: 2024-08-13 23:08:47.582994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81521565f790"
down_revision: Union[str, None] = "71994c9970cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("link", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "link")
    # ### end Alembic commands ###
