"""Add refund column to payments

Revision ID: dd7fa08c745c
Revises: 3f9e8a5e10f8
Create Date: 2024-08-07 11:09:34.467210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd7fa08c745c"
down_revision: Union[str, None] = "3f9e8a5e10f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("is_refunded", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE payments SET is_refunded = FALSE WHERE is_refunded IS NULL"
    )
    op.alter_column("payments", "is_refunded", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "is_refunded")
    # ### end Alembic commands ###
